# default_args is used to include configs from the _modular folder into this config. This ensures a modular way of combining different config files.
default_args: ["configs/_modular/sample_generation.yaml"]

############ modification of default args
sample_generation:
  stride: 1

############ non-default args
forest_path: 'data/val/color_grp_full_tile_97.laz' # path to forest point cloud for which validation tiles are to be generated
# forest_path: '../../results/test/20251028_094304_test_multi_as_tree_semantic/0/temp_train/validation_set/forest/color_grp_full_tile_97.laz' # path to forest point cloud for which validation tiles are to be generated
