defaults:
- visualization: eval
num_workers: 0
batch_size: 1
cuda: 0
weight_name: latest
enable_cudnn: true
checkpoint_dir: /home/pdm/models/SegmentAnyTree/model_file
model_name: PointGroup-PAPER
precompute_multi_scale: true
enable_dropout: false
voting_runs: 1
data:
  fold:
  - /home/nibio/mutable-outside-world/processed_data_full/treeinsfused/raw/MLS/MLS_test_mls_1_test.ply
tracker_options:
  full_res: true
  make_submission: true
  ply_output: maciej_eval.ply
hydra:
  run:
    dir: ${checkpoint_dir}/eval/${now:%Y-%m-%d_%H-%M-%S}
