tiles_loader:
  root_src: /home/pdm
  original_file_path: data/Barmasse_2023/Barmasse_2023_AllScans_Raw_Georef.laz
  results_destination: data/Barmasse_2023
  tiles_destination: ${tiles_loader.results_destination}/Barmasse_2023_AllScans_Raw_Georef_wo_overlap_${tiles_loader.tiling.tile_size}m
  preprocess:
    do_remove_hanging_points: True
    do_flatten: True
    do_remove_duplicates: True
  tiling:
    tile_size: 100
    tile_size_x: 500
    tile_size_y: 20
    pack_size: 1
  trimming:
    method: tree  # choose between {'drop', 'tree'}
    tree_list: [10, 5, 1]  # if method=tree, number of samples per level
    do_remove_empties: True # use of the classifier to remove the tiles that have no predictions classified as tree