tiles_loader:
  root_src: /home/pdm
  original_file_path: data/totile/Barmasse_2024_AllScans_Subsample4cm.las
  results_destination: data/tiling
  tiles_destination: ${tiles_loader.results_destination}/Barmasse_2024_AllScans_Subsample4cm_${tiles_loader.tiling.tile_size}m
  preprocess:
    do_remove_hanging_points: True
    do_flatten: True
    do_remove_duplicates: True
  tiling:
    tile_size: 100
    pack_size: 1
  trimming:
    method: tree  # choose between {'drop', 'tree'}
    tree_list: [10, 5, 1]  # if method=tree, number of samples per level
    do_remove_empties: True # use of the classifier to remove the tiles that have no predictions classified as tree